### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by prologic** [NicoNex/tau#26]
As per title :)

@[NicoNex] You _might_ be able to fix the tests faster than I can, I'm still trying to wrap my head around the codebase 😅

**Comment by NicoNex** [comment]
I've fixed the tests but apparently on Go versions prior to 1.18 `reflect.Pointer` was called `reflect.Ptr` so of course the compiler raises an error.
At this point I think I might update the go version in the `go.mod` to 1.18 and remove the testing for Go 1.17.x.

**Comment by prologic** [comment]
Yeap I would do that. Obviously there's no guarantees made about the API of _some_ libraries, so that makes sense.

**Comment by prologic** [comment]
Also what are we using reflect for anyway?

**Comment by NicoNex** [comment]
> Yeap I would do that. Obviously there's no guarantees made about the API of _some_ libraries, so that makes sense.

The guys on Debian 11 and a couple of other distros won't be happy though 😂.

**Comment by NicoNex** [comment]
> Also what are we using reflect for anyway?

It's being used for the plugin system.

**Comment by prologic** [comment]
> > Yeap I would do that. Obviously there's no guarantees made about the API of _some_ libraries, so that makes sense.
> 
> The guys on Debian 11 and a couple of other distros won't be happy though 😂.

Oh well they can upgrade their Go compiler or use a prebuilt binary release 😆

**Comment by NicoNex** [comment]
Resolved with f382eb0d78e37885766360c14adac5884a260912.

**Comment by NicoNex** [comment]
While working with the reflections for the plugin system I found out that they've defined a const in the reflect package for retrocompatibility `const Ptr = Pointer`.
So I reverted to Go 1.15 to keep Debian 11 and the users of other LTS distros happy. 😆

**Comment by prologic** [comment]
Type aliases ftw 😅
