### ISSUE TITLE
Reading/Writing to files

### ISSUE THREAD

**Issue by Xanderplayz16** [NicoNex/tau#48]
This is an essential to any programming language, and should be added. You could do something like an `open(filename)` that returns a object with functions like `read()` and `write()`, functions that read from (`read(filename)`) and write to (`write(filename, data)`) a file, or something else.

**Comment by NicoNex** [comment]
This is currently doable using `stdlib/os.tau` and I'm currently working on expanding the module features.

**Comment by Xanderplayz16** [comment]
> This is currently doable using `stdlib/os.tau` and I'm currently working on expanding the module features.

Thanks! I had no idea there was a stdlib.
