### ISSUE TITLE
Single quotes cannot be used to define strings

### ISSUE THREAD

**Issue by Xanderplayz16** [NicoNex/tau#50]
I noticed today that you cannot use single quotes to define strings. Adding this would make things easier for new users, who are used to single quotes (like me).

**Comment by NicoNex** [comment]
I prefer to keep things simple with Tau, if there's already a way to define strings at the moment and I would rather not add something that does exactly the same thing.
I was rather thinking of using single quotes for bytes (like in C or Go), but I have to think about this more.
